name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Publish self-contained
      run: dotnet publish --configuration Release --runtime win-x64 --self-contained true --output ./publish
      
    - name: Create ZIP archive
      run: |
        cd publish
        Compress-Archive -Path * -DestinationPath ../Blueshot-Standalone-${{ github.ref_name }}.zip
        cd ..
      shell: powershell
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blueshot-standalone
        path: Blueshot-Standalone-*.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Blueshot ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## What's New
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed release notes.
          
          ## Installation Options
          
          1. **Portable ZIP**: Download and extract anywhere
          2. **Quick Install**: Extract and run `Install.bat`
          3. **Professional Installer**: Coming soon
          
          ## System Requirements
          
          - Windows 10/11 (x64)
          - No additional dependencies required (self-contained)
          
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Blueshot-Standalone-${{ github.ref_name }}.zip
        asset_name: Blueshot-Standalone-${{ github.ref_name }}.zip
        asset_content_type: application/zip
